Mvc_Proje_3/WebApplication9/Controllers/OlusturController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using WebApplication9.DAL;
using WebApplication9.Models;

namespace WebApplication9.Controllers
{
    public class OlusturController : Controller
    {
        private KayitContext db = new KayitContext();

        // GET: Olustur
        public ActionResult Index()
        {
            var olusturulanlar = db.Olusturulanlar.Include(o => o.Kategori);
            return View(olusturulanlar.ToList());
        }

        // GET: Olustur/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Olustur olustur = db.Olusturulanlar.Find(id);
            if (olustur == null)
            {
                return HttpNotFound();
            }
            return View(olustur);
        }

        // GET: Olustur/Create
        public ActionResult Create()
        {
            ViewBag.KategoriId = new SelectList(db.Kategoriler, "Id", "Ad");
            return View();
        }

        // POST: Olustur/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,KategoriId,Baslik,Dil,Aciklama,foto1,Yazi")] Olustur olustur ,HttpPostedFileBase file)
        {
            using (KayitContext context = new KayitContext())
            {
                Olustur _slide = new Olustur();
                if (file != null && file.ContentLength > 0)
                {
                    MemoryStream memoryStream = file.InputStream as MemoryStream;
                    if (memoryStream == null)
                    {
                        memoryStream = new MemoryStream();
                        file.InputStream.CopyTo(memoryStream);
                    }
                    _slide.foto1 = memoryStream.ToArray();
                }
                _slide.Baslik = olustur.Baslik;
                _slide.KategoriId = olustur.KategoriId;
                _slide.Dil = olustur.Dil;
                _slide.Aciklama = olustur.Aciklama;
                _slide.Yazi = olustur.Yazi;
                db.Olusturulanlar.Add(_slide);
                db.SaveChanges();
            }

            ViewBag.KategoriId = new SelectList(db.Kategoriler, "Id", "Ad", olustur.KategoriId);
            return RedirectToAction("Index");
        }

        // GET: Olustur/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Olustur olustur = db.Olusturulanlar.Find(id);
            if (olustur == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriId = new SelectList(db.Kategoriler, "Id", "Ad", olustur.KategoriId);
            return View(olustur);
        }

        // POST: Olustur/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,KategoriId,Baslik,Dil,Aciklama,foto1,Yazi")] Olustur olustur ,HttpPostedFileBase file)
        {
            using (KayitContext context = new KayitContext())
            {
                Olustur _slide = new Olustur();
                if (file != null && file.ContentLength > 0)
                {
                    MemoryStream memoryStream = file.InputStream as MemoryStream;
                    if (memoryStream == null)
                    {
                        memoryStream = new MemoryStream();
                        file.InputStream.CopyTo(memoryStream);
                    }
                    _slide.foto1 = memoryStream.ToArray();
                }
                _slide.Baslik = olustur.Baslik;
                _slide.KategoriId = olustur.KategoriId;
                _slide.Dil = olustur.Dil;
                _slide.Aciklama = olustur.Aciklama;
                _slide.Yazi = olustur.Yazi;
                db.Olusturulanlar.Add(_slide);
                db.SaveChanges();
            }

            ViewBag.KategoriId = new SelectList(db.Kategoriler, "Id", "Ad", olustur.KategoriId);
            return RedirectToAction("Index");
        }

        // GET: Olustur/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Olustur olustur = db.Olusturulanlar.Find(id);
            if (olustur == null)
            {
                return HttpNotFound();
            }
            return View(olustur);
        }

        // POST: Olustur/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Olustur olustur = db.Olusturulanlar.Find(id);
            db.Olusturulanlar.Remove(olustur);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Kategori(int id)
        {
            string kategoriAdi = (from k in db.Kategoriler
                                  where k.Id == id
                                  select k.Ad).FirstOrDefault();
            ViewBag.Title = kategoriAdi + "Kategorisindeki Ürünler";
            ViewBag.Id = id;
            List<Olustur> olusturulanlar = (from u in db.Olusturulanlar
                                            where u.KategoriId == id
                                            select u).ToList();
            return View(olusturulanlar);
        }
        [HttpPost]
        public ActionResult sayfa(string itemId)
        {
            if (itemId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Olustur bSayfa = db.Olusturulanlar.Find(Convert.ToInt32(itemId));
            if (bSayfa == null)
            {
                return HttpNotFound();
            }
            return View(bSayfa);
        }

        public ActionResult Index1()
        {
            var res = db.Olusturulanlar.OrderByDescending(x => x.Id);
            var olusturulanlar = db.Olusturulanlar.Include(o => o.Kategori);
            return View(res.ToList());
        }
        

    }
}

Mvc_Proje_3/WebApplication9/Controllers/iletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebApplication9.Models;

namespace WebApplication9.Controllers
{
    public class iletisimController : Controller
    {
        // GET: iletisim
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(iletisimModel model)
        {
            if (ModelState.IsValid)
            {
                var body = new StringBuilder();
                body.AppendLine("İsim: " + model.FullName);
                body.AppendLine("Eposta: " + model.Email);
                body.AppendLine("Konu: " + model.Message);

                Gmail.SendMail(body.ToString());
                ViewBag.Success = true;
            }

            return View();
        }
    }
}

Mvc_Proje_3/WebApplication9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Writers</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Writers", "Index1", "Olustur", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Türler İçin Tıklayınız" aria-expanded="false">
                        @Html.Label(WebApplication9.Resources.dil.turler)
                        <b class="caret"></b>
                        </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink(WebApplication9.Resources.dil.makale, "/Kategori/2", "Olustur")</li>
                        <li>@Html.ActionLink(WebApplication9.Resources.dil.deneme, "/Kategori/3", "Olustur")</li>
                        <li>@Html.ActionLink(WebApplication9.Resources.dil.elestiri, "/Kategori/5", "Olustur")</li>
                        <li>@Html.ActionLink(WebApplication9.Resources.dil.masal, "/Kategori/4", "Olustur")</li>
                        <li>@Html.ActionLink(WebApplication9.Resources.dil.fikra, "/Kategori/7", "Olustur")</li>
                        <li>@Html.ActionLink(WebApplication9.Resources.dil.geziyazisi, "/Kategori/6", "Olustur")</li>
                    </ul>
                    </li>
                    <li>@Html.ActionLink(WebApplication9.Resources.dil.olustur, "Index", "Olustur")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Topluluk İçin Tıklayınız" aria-expanded="false">
                            @Html.Label(WebApplication9.Resources.dil.topluluk)
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink(WebApplication9.Resources.dil.turlerhakkinda, "TurHakkinda", "Home")</li>
                            <li>@Html.ActionLink(WebApplication9.Resources.dil.turlerinyazarlari, "TurYazar", "Home")</li>
                            <li>@Html.ActionLink(WebApplication9.Resources.dil.hakkinda, "Hakkimizda", "Home")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink(WebApplication9.Resources.dil.iletisim, "Index", "iletisim")</li>
                    
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>

                    <li class="page-scroll">

                    </li>

                    <li class="page-scroll">
                        <div class="dropdown">
                            <h5>                               </h5>
                            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                                Dil
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header">Default Türkçe</li>
                                <li>@Html.ActionLink("TR", "DilDegistir", "Home", new { dil = "tr" }, null)</li>
                                <li>@Html.ActionLink("ENG", "DilDegistir", "Home", new { dil = "en" }, null)</li>
                            </ul>
                        </div>
                    </li>

                    <li class="page-scroll">
                        <h5>                                         </h5>
                        <button type="button" class="btn btn-primary">
                            @WebApplication9.Resources.dil.giris
                        </button>
                    </li>
                </ul>
                <div class="container">
                    <div class="row">
                        <h5>                 </h5>
                        <div id="custom-search-input">
                            <div class="input-group col-md-3">
                                <input type="text" class="search-query form-control" placeholder="Search" />
                                <span class="input-group-btn">
                                    <button class="btn btn-danger" type="button">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <div class="row">
                    <div class="col-md-4" >
                         <h3> 
                        @Html.Label(WebApplication9.Resources.dil.amatoryazartop)
                         </h3>
                    </div>
                    <div class="col-md-4">

                    </div>

                    <div class="col-md-4">
                        <div class="exsprite">

                            <ul class="social-icons pull-right">

                                <li><a class="icon google" href="https://www.gmail.com/">Google+</a></li>
                                <li><a class="icon facebook" href="https://www.facebook.com/">Facebook</a></li>
                                <li><a class="icon twitter" href="https://www.twitter.com">Twitter</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Mvc_Proje_3/WebApplication9/Views/Shared/_Turicerik.cshtml
<p>Partial Bölümü Tema Ayarlanınca Değişecektir.</p>